version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Monta o diretório do projeto local no container
      - /app/node_modules  # Garante que node_modules seja gerenciado internamente no container
    user: "1000:1000"  # Define o UID e GID para garantir acesso
    env_file:
      - .env
    stdin_open: true
    tty: true
